AWSTemplateFormatVersion: 2010-09-09
Resources:
  HaruBotFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: ./release/app.zip
      FunctionName: HaruBotFunction
      Handler: index.handler
      Runtime: nodejs12.x
      Role:
        Fn::GetAtt:
          - "HaruBotRole"
          - "Arn"
      MemorySize: 512
      Timeout: 10
      Environment:
        Variables:
          TZ: Asia/Tokyo
          ACCESSTOKEN: ~~
          CHANNELSECRET: ~~

  ReplyMapping:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ReplyMapping
      AttributeDefinitions:
        - AttributeName: type
          AttributeType: S
      KeySchema:
        - AttributeName: type
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 3
        WriteCapacityUnits: 3

  HaruBotRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "edgelambda.amazonaws.com"
                - "lambda.amazonaws.com"
                - "dynamodb.amazonaws.com"
                - "cloudwatch.amazonaws.com"
            Action:
              - sts:AssumeRole